module ToolsList
	def tools
		[
			{ :id => 145, :name => "Alchemist's supplies", :cost => 50, :weight => 8, :category => "Artisan" },
			{ :id => 145, :name => "Brewer's supplies", :cost => 20, :weight => 8, :category => "Artisan" },
			{ :id => 147, :name => "Calligrapher's supplies", :cost => 10, :weight => 5, :category => "Artisan" },
			{ :id => 148, :name => "Carpenter's supplies", :cost => 8, :weight => 6, :category => "Artisan" },
			{ :id => 149, :name => "Carographer's tools", :cost => 15, :weight => 6, :category => "Artisan" },
			{ :id => 150, :name => "Cobbler's tools", :cost => 5, :weight => 5, :category => "Artisan" },
			{ :id => 151, :name => "Cooks's utensils", :cost => 1, :weight => 8, :category => "Artisan" },
			{ :id => 152, :name => "Glassblower's tools", :cost => 30, :weight => 5, :category => "Artisan" },
			{ :id => 153, :name => "Jeweler's tools", :cost => 25, :weight => 2, :category => "Artisan" },
			{ :id => 154, :name => "Leatherworker's tools", :cost => 5, :weight => 5, :category => "Artisan" },
			{ :id => 155, :name => "Mason's tools", :cost => 10, :weight => 8, :category => "Artisan" },
			{ :id => 156, :name => "Painter's supplies", :cost => 10, :weight => 5, :category => "Artisan" },
			{ :id => 157, :name => "Potter's tools", :cost => 10, :weight => 3, :category => "Artisan" },
			{ :id => 158, :name => "Smith's tools", :cost => 20, :weight => 8, :category => "Artisan" },
			{ :id => 159, :name => "Tinker's tools", :cost => 50, :weight => 10, :category => "Artisan" },
			{ :id => 160, :name => "Weaver's tools", :cost => 1, :weight => 5, :category => "Artisan" },
			{ :id => 161, :name => "Woodcarver's tools", :cost => 1, :weight => 5, :category => "Artisan" },
			{ :id => 162, :name => "Disguise kit", :cost => 25, :weight => 3 },
			{ :id => 163, :name => "Forgery kit", :cost => 15, :weight => 5 },
			{ :id => 164, :name => "Dice set", :cost => 0.1, :weight => 0, :category => "Gaming set" },
			{ :id => 165, :name => "Dragonchess set", :cost => 1, :weight => 0.25, :category => "Gaming set" },
			{ :id => 166, :name => "Playing card set", :cost => 0.5, :weight => 0, :category => "Gaming set" },
			{ :id => 167, :name => "Three-Dragon Ante set", :cost => 1, :weight => 0, :category => "Gaming set" },
			{ :id => 168, :name => "Herbalism kit", :cost => 5, :weight => 3 },
			{ :id => 169, :name => "Bagpipes", :cost => 30, :weight => 6, :category => "Musical instrument" },
			{ :id => 170, :name => "Drums", :cost => 6, :weight => 3, :category => "Musical instrument" },
			{ :id => 171, :name => "Dulcimer", :cost => 25, :weight => 10, :category => "Musical instrument" },
			{ :id => 172, :name => "Flute", :cost => 2, :weight => 1, :category => "Musical instrument" },
			{ :id => 173, :name => "Lute", :cost => 35, :weight => 2, :category => "Musical instrument" },
			{ :id => 174, :name => "Lyre", :cost => 30, :weight => 2, :category => "Musical instrument" },
			{ :id => 175, :name => "Horn", :cost => 3, :weight => 2, :category => "Musical instrument" },
			{ :id => 176, :name => "Pan Flute", :cost => 12, :weight => 2, :category => "Musical instrument" },
			{ :id => 177, :name => "Shawm", :cost => 2, :weight => 1, :category => "Musical instrument" },
			{ :id => 178, :name => "Viol", :cost => 30, :weight => 1, :category => "Musical instrument" },
			{ :id => 179, :name => "Navigator's tools", :cost => 25, :weight => 2 },
			{ :id => 180, :name => "Poisoner's kit", :cost => 50, :weight => 2 },
			{ :id => 181, :name => "Theive's tools", :cost => 25, :weight => 1 },
		]
	end

end