# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b48ce1e89bf528985835f6d1d98858517a30a4effa55d5f6601e092975af37c4bb41ce59869abeae6e6ecddf44c50658d795a88c03cf74456e2fe12e59394ee

test:
  secret_key_base: a6dcc9fa6cbbc0edb0faffdacba38894597f37bfbf61e3b68dffb3f139b8a7e23a146cefdd8e2fdae7e7652f246397b1967b2af92af633ae76b237dbe2d3fa2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
